name: flutter_crypto_wallet_integration
description: A sample flutter app to test a crypto wallet integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.2
  walletconnect_dart: ^0.0.10
  google_fonts: ^4.0.4
  slider_button: ^2.0.0
  web3dart: ^2.3.5
  wallet_connect: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_inappwebview: ^5.4.3+7
  eth_sig_util: ^0.0.9
  http: ^0.13.4
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
